---
- name: Install Docker on Frankfurt Server
  hosts: webservers
  become: yes

  tasks:
    - name: Step 1 - Update the phonebook
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Step 2 - Remove Compose V1
      apt:
        name: docker-compose
        state: absent

    - name: Step 3 - Install Docker and Compose V2
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Step 3 - Turn on the Docker Engine
      systemd:
        name: docker
        state: started
        enabled: yes
